language: php

php:
  - 7.0

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

before_script:
  - composer install --prefer-dist --no-interaction
  - cp .env.travis .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit --debug
  - vendor/bin/phpcs app --standard=PSR2
