language: php

php:
  - 7.0

services:
  - mysql

sudo: true

before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'

before_script:
  - composer install --prefer-dist --no-interaction
  - cp .env.travis .env
  - php artisan key:generate
  - bash .travis.install-mysql-5.7.sh

script:
  - vendor/bin/phpunit --debug
  - vendor/bin/phpcs app --standard=PSR2
